all:
	wget https://zenodo.org/record/3271522/files/proppy_1.0.train.tsv
	wget https://zenodo.org/record/3271522/files/proppy_1.0.test.tsv
	wget https://zenodo.org/record/3271522/files/proppy_1.0.dev.tsv

clean:
	rm proppy_1.0.{train,test,dev}.tsv